const Constants = {
  createAccount: "Create Account",
  name: "Your Name",
  email: "Email",
  password: "Password",
  phoneNumber: "Phone Number",
  originalPrice: "Original Price: ",
  newPrice: "New Price: ",
  about: "About this item: ",
  cart: "ADD TO CART ",
  wishlist: " WISHLIST",
  signUp: "Sign Up",
  signIn: "Sign In",
  accountCheck: "Already Have an account?",
  successMsg: "New User added Successfully",
  errorMsg: "User Already Exists",
  missingFields: "Please Fill all required fields",
  ownersName: "Owner's Name: ",
  ownersContact: "Owner's Contact:",
  ownersEmail: "Owner's Email:",
  aboutthisItem: "About this item: ",
  autoCloseTime: 5000,
  inclusive: "inclusive of all taxes",
};

export default Constants;
